### ISSUE TITLE
Migrations fail on new install with missing index

### ISSUE THREAD

**Issue by adammcmaster** [zooniverse/talk-api#213]
The migrations appear to be broken:

```
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

Index name 'index_discussions_on_board_id_and_sticky_and_sticky_position_and_updated_at' on table 'discussions' does not exist
/usr/local/bundle/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:1002:in `index_name_for_remove'
/usr/local/bundle/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:593:in `remove_index'
/usr/local/bundle/gems/schema_plus_indexes-0.2.4/lib/schema_plus/indexes/remove_if_exists.rb:10:in `remove_index'
/usr/local/bundle/gems/schema_plus_indexes-0.2.4/lib/schema_plus/indexes/remove_if_exists.rb:10:in `remove_index'
/usr/local/bundle/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:665:in `block in method_missing'
/usr/local/bundle/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:634:in `block in say_with_time'
/usr/local/bundle/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:634:in `say_with_time'
/usr/local/bundle/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:654:in `method_missing'
/rails_app/db/migrate/20150928165922_add_comment_created_at_to_discussions.rb:5:in `change'
/usr/local/bundle/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:608:in `exec_migration'
/usr/local/bundle/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:592:in `block (2 levels) in migrate'
/usr/local/bundle/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:591:in `block in migrate'
/usr/local/bundle/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/usr/local/bundle/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:590:in `migrate'
/usr/local/bundle/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:768:in `migrate'
/usr/local/bundle/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:1023:in `block in execute_migration_in_transaction'
/usr/local/bundle/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:1069:in `block in ddl_transaction'
/usr/local/bundle/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/usr/local/bundle/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/usr/local/bundle/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/usr/local/bundle/gems/activerecord-4.2.11.1/lib/active_record/transactions.rb:220:in `transaction'
/usr/local/bundle/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:1069:in `ddl_transaction'
/usr/local/bundle/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:1022:in `execute_migration_in_transaction'
/usr/local/bundle/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:984:in `block in migrate'
/usr/local/bundle/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:980:in `each'
/usr/local/bundle/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:980:in `migrate'
/usr/local/bundle/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:823:in `up'
/usr/local/bundle/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:801:in `migrate'
/usr/local/bundle/gems/activerecord-4.2.11.1/lib/active_record/tasks/database_tasks.rb:139:in `migrate'
/usr/local/bundle/gems/activerecord-4.2.11.1/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
/usr/local/bundle/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'

Caused by:
ArgumentError: Index name 'index_discussions_on_board_id_and_sticky_and_sticky_position_and_updated_at' on table 'discussions' does not exist
/usr/local/bundle/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:1002:in `index_name_for_remove'
/usr/local/bundle/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:593:in `remove_index'
/usr/local/bundle/gems/schema_plus_indexes-0.2.4/lib/schema_plus/indexes/remove_if_exists.rb:10:in `remove_index'
/usr/local/bundle/gems/schema_plus_indexes-0.2.4/lib/schema_plus/indexes/remove_if_exists.rb:10:in `remove_index'
/usr/local/bundle/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:665:in `block in method_missing'
/usr/local/bundle/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:634:in `block in say_with_time'
/usr/local/bundle/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:634:in `say_with_time'
/usr/local/bundle/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:654:in `method_missing'
/rails_app/db/migrate/20150928165922_add_comment_created_at_to_discussions.rb:5:in `change'
/usr/local/bundle/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:608:in `exec_migration'
/usr/local/bundle/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:592:in `block (2 levels) in migrate'
/usr/local/bundle/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:591:in `block in migrate'
/usr/local/bundle/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/usr/local/bundle/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:590:in `migrate'
/usr/local/bundle/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:768:in `migrate'
/usr/local/bundle/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:1023:in `block in execute_migration_in_transaction'
/usr/local/bundle/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:1069:in `block in ddl_transaction'
/usr/local/bundle/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/usr/local/bundle/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/usr/local/bundle/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/usr/local/bundle/gems/activerecord-4.2.11.1/lib/active_record/transactions.rb:220:in `transaction'
/usr/local/bundle/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:1069:in `ddl_transaction'
/usr/local/bundle/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:1022:in `execute_migration_in_transaction'
/usr/local/bundle/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:984:in `block in migrate'
/usr/local/bundle/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:980:in `each'
/usr/local/bundle/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:980:in `migrate'
/usr/local/bundle/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:823:in `up'
/usr/local/bundle/gems/activerecord-4.2.11.1/lib/active_record/migration.rb:801:in `migrate'
/usr/local/bundle/gems/activerecord-4.2.11.1/lib/active_record/tasks/database_tasks.rb:139:in `migrate'
/usr/local/bundle/gems/activerecord-4.2.11.1/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
/usr/local/bundle/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

**Comment by camallen** [comment]
OOI did you run the migrations after fresh db creation? this can be problematic as the migration schema changes can get out of sync.

best to restore the schema and then run any missing migrations, the below should work but talk might need the FDW tables setup etc... it's non standard, https://github.com/zooniverse/Talk-Api#setting-up
```
RACK_ENV=test bundle exec rake db:create
RACK_ENV=test bundle exec rake db:schema:load
RACK_ENV=panoptes_test bundle exec rake db:create
RACK_ENV=test bundle exec rake panoptes:db:create_tables
RACK_ENV=test bundle exec rake panoptes:db:setup
```

**Comment by camallen** [comment]
I've update the instructions on the readme (#235) and tested the database schema is created correctly / migrations can run. See https://github.com/zooniverse/talk-api#setting-up

I'm going to close this now - feel free to reopen
